-- Configure buffer local auto commands to add when attaching a language server
return {
  -- first key is the `augroup` to add the auto commands to (:h augroup)
  -- lsp_vectorcode_register = {
  --   {
  --     event = { "LspAttach" },
  --     desc = "Register buffer for VectorCode",
  --     callback = function(args)
  --       local cacher = require("vectorcode.config").get_cacher_backend()
  --       cacher.async_check(
  --         "config",
  --         function()
  --           cacher.register_buffer(args.buf, {
  --             n_query = 10,
  --           })
  --         end,
  --         nil
  --       )
  --     end,
  --   },
  -- },
}
