-- AstroNvim 기본 플러그인 비활성화 목록
return {
  { "rebelot/heirline.nvim", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "nvimtools/none-ls.nvim", enabled = false },
  { "jay-babu/mason-null-ls.nvim", enabled = false },
  { "hrsh7th/nvim-cmp", enabled = false },
  { "rcarriga/cmp-dap", enabled = false },
  { "L3MON4D3/LuaSnip", enabled = false },
  { "stevearc/aerial.nvim", enabled = false },
  { "windwp/nvim-autopairs", enabled = false },
  { "HiPhish/rainbow-delimiters.nvim", enabled = false },
  { "akinsho/toggleterm.nvim", enabled = false },
  { "rcarriga/nvim-dap-ui", enabled = false },
  { "nvim-neotest/nvim-nio", enabled = false },
  { "stevearc/resession.nvim", enabled = false },
  { "nvim-telescope/telescope.nvim", enabled = false },
  { "nvim-telescope/telescope-file-browser.nvim", enabled = false },
  { "piersolenski/telescope-import.nvim", enabled = false },
}
